# Generated by Django 5.0.1 on 2024-10-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='def.name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='def.surname', max_length=50),
        ),
    ]
